'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { type ReactNode, useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Check, Clock3, Layers3, Loader2, RefreshCw } from 'lucide-react';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { OfficialTemplate, OfficialTemplateVersion, collaborationApi } from '@/lib/collaboration-api';

function templateById(items:OfficialTemplate[],id:string){for(const item of items){if(item.template.id===id)return item}return null;}
function versionById(items:OfficialTemplateVersion[],id:string){for(const item of items){if(item.id===id)return item}return null;}
function materializeTemplates(items:OfficialTemplate[],selectedId:string,select:(item:OfficialTemplate)=>void){const nodes:ReactNode[]=[];for(const item of items){const selected=item.template.id===selectedId;nodes.push(<button type="button" key={item.template.id} className={`w-full border-b px-4 py-4 text-left last:border-b-0 ${selected?'bg-muted':''}`} onClick={()=>select(item)}><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{item.template.name}</span><Badge variant="outline">v{item.current_version?.version??'-'}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.template.description}</p><p className="mt-2 font-mono text-xs text-muted-foreground">{item.template.app_type}</p></button>)}return nodes;}
function materializeVersions(items:OfficialTemplateVersion[],selectedId:string,select:(id:string)=>void){const nodes:ReactNode[]=[];for(const item of items){nodes.push(<Button key={item.id} type="button" size="sm" variant={item.id===selectedId?'default':'outline'} onClick={()=>select(item.id)}>v{item.version}</Button>)}return nodes;}

export default function OfficialTemplatesPage(){const router=useRouter();const [templates,setTemplates]=useState<OfficialTemplate[]>([]);const [versions,setVersions]=useState<OfficialTemplateVersion[]>([]);const [selectedId,setSelectedId]=useState('');const [versionId,setVersionId]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{const items=await collaborationApi.templates();setTemplates(items);if(selectedId===''){for(const item of items){setSelectedId(item.template.id);setVersionId(item.current_version?.id??'');break}}},[selectedId]);useEffect(()=>{void load().catch((value:unknown)=>setError(value instanceof Error?value.message:'模板目录加载失败'));},[load]);
 const select=async(item:OfficialTemplate)=>{setSelectedId(item.template.id);setVersionId(item.current_version?.id??'');setError('');try{setVersions(await collaborationApi.versions(item.template.id))}catch(value){setError(value instanceof Error?value.message:'模板版本加载失败')}};
 const create=async()=>{const current=templateById(templates,selectedId);if(!current||!name.trim())return;setBusy('create');setError('');setMessage('');try{const project=await collaborationApi.createFromTemplate(current.template.slug,versionId,name,description);setMessage('项目已从已验证模板创建');router.push(`/workspace?project=${encodeURIComponent(project.project_id)}`)}catch(value){setError(value instanceof Error?value.message:'模板项目创建失败')}finally{setBusy('')}};
 const selected=templateById(templates,selectedId);const selectedVersion=versionById(versions,versionId)??selected?.current_version??null;const templateNodes=materializeTemplates(templates,selectedId,(item)=>void select(item));const versionNodes=materializeVersions(versions,versionId,setVersionId);
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b bg-card"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><Button asChild size="icon" variant="ghost" title="返回项目列表"><Link href="/projects"><ArrowLeft className="h-4 w-4"/></Link></Button><Layers3 className="h-5 w-5"/><h1 className="text-base font-semibold">官方模板</h1></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>刷新</Button></div></header><div className="mx-auto grid max-w-6xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[320px_minmax(0,1fr)]"><section className="border" aria-label="官方模板目录">{templateNodes.length>0?templateNodes:<p className="p-4 text-sm text-muted-foreground">暂无已发布模板</p>}</section><section className="space-y-5"><div className="border-b pb-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">{selected?.template.name??'选择模板'}</h2>{selectedVersion&&<Badge variant="outline">SHA {selectedVersion.checksum_sha256.slice(0,12)}</Badge>}</div><p className="mt-2 text-sm text-muted-foreground">{selected?.template.description??'从左侧选择一个官方模板。'}</p></div>{selected&&<><div><div className="mb-2 flex items-center gap-2 text-sm font-medium"><Clock3 className="h-4 w-4"/>版本</div><div className="flex flex-wrap gap-2">{versionNodes.length>0?versionNodes:<Button size="sm" variant="default">v{selected.current_version?.version??'-'}</Button>}</div></div><div className="grid gap-3"><Input aria-label="项目名称" placeholder="项目名称" value={name} onChange={(event)=>setName(event.target.value)}/><Input aria-label="项目描述" placeholder="项目描述" value={description} onChange={(event)=>setDescription(event.target.value)}/><Button className="w-fit" disabled={busy!==''||!name.trim()||!versionId} onClick={()=>void create()}>{busy==='create'?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Layers3 className="mr-2 h-4 w-4"/>}使用此版本创建项目</Button></div></>}{(error||message)&&<Alert variant={error?'destructive':'default'}><AlertTitle>{error?'操作失败':'操作完成'}</AlertTitle><AlertDescription className="flex items-center gap-2">{!error&&<Check className="h-4 w-4"/>}{error||message}</AlertDescription></Alert>}</section></div></main>}
