import { useWorkspaceImplementationGenerationAction } from './use-workspace-implementation-generation-action';
import { useWorkspacePlanImplementationAction } from './use-workspace-plan-implementation-action';
import type {
  ImplementationActionOptions,
  WorkspaceOrchestrationImplementationActionsContract,
} from './workspace-orchestration-action-types';

export function useWorkspaceOrchestrationImplementationActions({
  projectInfo,
  chatMode,
  isOnline,
  selectedModel,
  availablePlans,
  recommendedPlanId,
  selectedPlanId,
  files,
  savedFiles,
  messagesRef,
  generationAbortRef,
  implementingPlanRef,
  autoPlanTriggeredRef,
  setProjectInfo,
  applyImplementationGenerationMessages,
  applyImplementationStreamPatchMessages,
  applyPlanImplementationMessages,
  applyGenerationStateMessages,
  setFiles,
  setSavedFiles,
  setIsGenerating,
  setIsStopConfirming,
  setGenerationStage,
  updatePlanFlowState,
  persistGenerationState,
  applyWorkspaceState,
  applyWorkflowStepToMessage,
  applyIncrementalWorkflowStep,
  setMessageStreamingState,
  yieldStepRender,
  reflectFilePathInTree,
  fetchProjectDetail,
  refreshProjectFileTree,
  fetchProjectCommits,
  ensureProjectRuntimeReady,
  safeParseJSON,
  appendStatusLine,
  appendReasoningChunk,
  normalizeWorkflowStep,
  getEventMessage,
  getGeneratedFilesFromEvent,
  getGuidanceFromEvent,
  createPersistedProject,
  persistWorkspaceProject,
  resolveStepEngineeringState,
}: ImplementationActionOptions): WorkspaceOrchestrationImplementationActionsContract {
  const handleLLMGenerate = useWorkspaceImplementationGenerationAction({
    projectInfo,
    chatMode,
    isOnline,
    selectedModel,
    files,
    savedFiles,
    generationAbortRef,
    applyImplementationGenerationMessages,
    applyGenerationStateMessages,
    setFiles,
    setSavedFiles,
    setIsGenerating,
    setIsStopConfirming,
    setGenerationStage,
    persistGenerationState,
    applyWorkflowStepToMessage,
    applyIncrementalWorkflowStep,
    setMessageStreamingState,
    yieldStepRender,
    reflectFilePathInTree,
    fetchProjectDetail,
    refreshProjectFileTree,
    fetchProjectCommits,
    safeParseJSON,
    appendStatusLine,
    appendReasoningChunk,
    applyImplementationStreamPatchMessages,
    normalizeWorkflowStep,
    getEventMessage,
    getGeneratedFilesFromEvent,
    getGuidanceFromEvent,
    resolveStepEngineeringState,
  });

  const choosePlanAndImplement = useWorkspacePlanImplementationAction({
    projectInfo,
    isOnline,
    availablePlans,
    recommendedPlanId,
    selectedPlanId,
    messagesRef,
    implementingPlanRef,
    autoPlanTriggeredRef,
    setProjectInfo,
    applyPlanImplementationMessages,
    applyWorkspaceState,
    ensureProjectRuntimeReady,
    createPersistedProject,
    persistWorkspaceProject,
    handleLLMGenerate,
    updatePlanFlowState,
  });

  return {
    choosePlanAndImplement,
    handleLLMGenerate,
  };
}
