import { useCallback } from 'react';

import type { WorkspaceProjectInfo } from './workspace-types';
import type { GenerateOptions } from './workspace-orchestration-hook-types';
import type {
  ImplementationGenerationActionOptions,
  WorkspaceImplementationGenerationActionContract,
} from './workspace-orchestration-implementation-action-types';
import { runWorkspaceImplementationGeneration } from './workspace-orchestration-execution';

export function useWorkspaceImplementationGenerationAction({
  projectInfo,
  chatMode,
  isOnline,
  selectedModel,
  files,
  savedFiles,
  generationAbortRef,
  applyImplementationGenerationMessages,
  applyImplementationStreamPatchMessages,
  applyGenerationStateMessages,
  setFiles,
  setSavedFiles,
  setIsGenerating,
  setIsStopConfirming,
  setGenerationStage,
  persistGenerationState,
  applyWorkflowStepToMessage,
  applyIncrementalWorkflowStep,
  setMessageStreamingState,
  yieldStepRender,
  reflectFilePathInTree,
  fetchProjectDetail,
  refreshProjectFileTree,
  fetchProjectCommits,
  safeParseJSON,
  appendStatusLine,
  appendReasoningChunk,
  normalizeWorkflowStep,
  getEventMessage,
  getGeneratedFilesFromEvent,
  getGuidanceFromEvent,
  resolveStepEngineeringState,
}: ImplementationGenerationActionOptions): WorkspaceImplementationGenerationActionContract {
  return useCallback(async (
    prompt: string,
    targetProject?: WorkspaceProjectInfo,
    options?: GenerateOptions,
  ) => {
    await runWorkspaceImplementationGeneration({
      prompt,
      targetProject,
      options,
      projectInfo,
      chatMode,
      isOnline,
      selectedModel,
      files,
      savedFiles,
      generationAbortRef,
      persistGenerationState,
      applyImplementationGenerationMessages,
      applyImplementationStreamPatchMessages,
      applyGenerationStateMessages,
      setFiles,
      setSavedFiles,
      setIsGenerating,
      setIsStopConfirming,
      setGenerationStage,
      applyWorkflowStepToMessage,
      applyIncrementalWorkflowStep,
      setMessageStreamingState,
      yieldStepRender,
      reflectFilePathInTree,
      fetchProjectDetail,
      refreshProjectFileTree,
      fetchProjectCommits,
      safeParseJSON,
      appendReasoningChunk,
      appendStatusLine,
      getEventMessage,
      getGeneratedFilesFromEvent,
      getGuidanceFromEvent,
      normalizeWorkflowStep,
      resolveStepEngineeringState,
    });
  }, [
    appendReasoningChunk,
    appendStatusLine,
    applyIncrementalWorkflowStep,
    applyWorkflowStepToMessage,
    chatMode,
    fetchProjectCommits,
    fetchProjectDetail,
    files,
    generationAbortRef,
    getEventMessage,
    getGeneratedFilesFromEvent,
    getGuidanceFromEvent,
    isOnline,
    normalizeWorkflowStep,
    persistGenerationState,
    projectInfo,
    reflectFilePathInTree,
    refreshProjectFileTree,
    resolveStepEngineeringState,
    safeParseJSON,
    savedFiles,
    selectedModel,
    setFiles,
    setGenerationStage,
    applyImplementationGenerationMessages,
    applyImplementationStreamPatchMessages,
    applyGenerationStateMessages,
    setIsGenerating,
    setIsStopConfirming,
    setMessageStreamingState,
    setSavedFiles,
    yieldStepRender,
  ]);
}
