'use client';

import { type ReactNode, useCallback, useEffect, useState } from 'react';
import { Check, FilePlus2, History, Loader2, RefreshCw, RotateCcw } from 'lucide-react';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { OfficialTemplate, OfficialTemplateVersion, TemplateFileInput, collaborationApi } from '@/lib/collaboration-api';

function findTemplate(items:OfficialTemplate[],id:string){for(const item of items){if(item.template.id===id)return item}return null;}
function parseFiles(raw:string):TemplateFileInput[]{const value:unknown=JSON.parse(raw);if(!Array.isArray(value))throw new Error('文件 JSON 必须是数组');const files:TemplateFileInput[]=[];for(const item of value){if(typeof item!=='object'||item===null)throw new Error('每个文件必须是对象');const record=item as Record<string,unknown>;if(typeof record.path!=='string'||typeof record.content!=='string')throw new Error('每个文件必须包含 path 和 content');files.push({path:record.path,content:record.content})}return files;}
function materializeTemplateOptions(items:OfficialTemplate[]){const nodes:ReactNode[]=[<option key="new" value="">发布新模板</option>];for(const item of items){nodes.push(<option key={item.template.id} value={item.template.id}>{item.template.name}</option>)}return nodes;}
function materializeVersionRows(items:OfficialTemplateVersion[],currentId:string,busy:string,rollback:(item:OfficialTemplateVersion)=>void){const nodes:ReactNode[]=[];for(const item of items){nodes.push(<div key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0"><div><div className="flex items-center gap-2 text-sm font-medium">v{item.version}{item.id===currentId&&<Badge>当前</Badge>}</div><p className="mt-1 font-mono text-xs text-muted-foreground">{item.checksum_sha256}</p></div>{item.id!==currentId&&<Button size="sm" variant="outline" disabled={busy!==''} onClick={()=>rollback(item)}><RotateCcw className="mr-2 h-4 w-4"/>回滚</Button>}</div>)}return nodes;}

const initialFiles='[\n  {"path":"index.html","content":"<h1>{{project_name}}</h1>"}\n]';
export default function AdminProjectTemplatesPage(){const [templates,setTemplates]=useState<OfficialTemplate[]>([]);const [versions,setVersions]=useState<OfficialTemplateVersion[]>([]);const [selectedId,setSelectedId]=useState('');const [slug,setSlug]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [appType,setAppType]=useState('static-html');const [files,setFiles]=useState(initialFiles);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setTemplates(await collaborationApi.adminTemplates())},[]);useEffect(()=>{void load().catch((value:unknown)=>setError(value instanceof Error?value.message:'官方模板加载失败'))},[load]);
 const select=async(id:string)=>{setSelectedId(id);const item=findTemplate(templates,id);if(!item){setSlug('');setName('');setDescription('');setAppType('static-html');setVersions([]);return}setSlug(item.template.slug);setName(item.template.name);setDescription(item.template.description);setAppType(item.template.app_type);try{setVersions(await collaborationApi.adminVersions(item.template.id))}catch(value){setError(value instanceof Error?value.message:'版本列表加载失败')}};
 const publish=async()=>{setBusy('publish');setError('');setMessage('');try{const current=findTemplate(templates,selectedId);await collaborationApi.publishTemplate({slug,name,description,app_type:appType,expected_current_version_id:current?.template.current_version_id??'',files:parseFiles(files)});setMessage('官方模板新版本已发布');await load()}catch(value){setError(value instanceof Error?value.message:'模板发布失败')}finally{setBusy('')}};
 const rollback=(version:OfficialTemplateVersion)=>{const current=findTemplate(templates,selectedId);if(!current||!window.confirm(`确认将 ${current.template.name} 回滚到 v${version.version}？`))return;setBusy('rollback');setError('');void collaborationApi.rollbackTemplate(current.template.id,version.id,current.template.current_version_id).then(async()=>{setMessage('模板当前版本已回滚');await load();await select(current.template.id)}).catch((value:unknown)=>setError(value instanceof Error?value.message:'模板回滚失败')).finally(()=>setBusy(''))};
 const current=findTemplate(templates,selectedId);const optionNodes=materializeTemplateOptions(templates);const versionNodes=materializeVersionRows(versions,current?.template.current_version_id??'',busy,rollback);
 return <main className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-3 border-b pb-4"><div><h1 className="text-xl font-semibold">官方项目模板</h1><p className="mt-1 text-sm text-muted-foreground">发布不可变版本，并通过 expected-current 门禁切换或回滚目录当前版本。</p></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>刷新</Button></header><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.7fr)]"><section className="space-y-4"><label className="grid gap-2 text-sm"><span className="font-medium">模板</span><select className="h-10 border bg-background px-3" value={selectedId} onChange={(event)=>void select(event.target.value)}>{optionNodes}</select></label><div className="grid gap-3 sm:grid-cols-2"><Input aria-label="模板标识" placeholder="template-slug" value={slug} disabled={selectedId!==''} onChange={(event)=>setSlug(event.target.value.toLowerCase())}/><Input aria-label="模板名称" placeholder="模板名称" value={name} onChange={(event)=>setName(event.target.value)}/><Input aria-label="应用类型" placeholder="static-html" value={appType} onChange={(event)=>setAppType(event.target.value)}/><Input aria-label="模板描述" placeholder="模板描述" value={description} onChange={(event)=>setDescription(event.target.value)}/></div><label className="grid gap-2 text-sm"><span className="font-medium">版本文件 JSON</span><Textarea className="min-h-56 font-mono text-xs" value={files} onChange={(event)=>setFiles(event.target.value)}/></label><Button disabled={busy!==''||!slug.trim()||!name.trim()} onClick={()=>void publish()}>{busy==='publish'?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<FilePlus2 className="mr-2 h-4 w-4"/>}发布新版本</Button></section><section className="space-y-4"><div className="flex items-center justify-between border-b pb-3"><h2 className="flex items-center gap-2 text-sm font-semibold"><History className="h-4 w-4"/>版本历史</h2><Badge variant="outline">{versions.length}</Badge></div>{selectedId?(versionNodes.length>0?versionNodes:<p className="text-sm text-muted-foreground">暂无版本</p>):<p className="text-sm text-muted-foreground">选择已有模板以查看版本和执行回滚。</p>}</section></div>{(error||message)&&<Alert variant={error?'destructive':'default'}><AlertTitle>{error?'操作失败':'操作完成'}</AlertTitle><AlertDescription className="flex items-center gap-2">{!error&&<Check className="h-4 w-4"/>}{error||message}</AlertDescription></Alert>}</main>}
