'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { type ReactNode, useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Check, Eye, Loader2, Pencil, RefreshCw, Shield, Trash2, UserPlus, Users } from 'lucide-react';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { CollaborationAudit, ProjectAccess, ProjectMember, collaborationApi } from '@/lib/collaboration-api';

function roleLabel(role:string){if(role==='owner')return '所有者';if(role==='editor')return '编辑者';return '查看者';}
function roleIcon(role:string){return role==='viewer'?<Eye className="h-4 w-4"/>:role==='editor'?<Pencil className="h-4 w-4"/>:<Shield className="h-4 w-4"/>;}
function auditLabel(action:string){if(action==='member_added')return '添加成员';if(action==='member_role_updated')return '修改角色';return '移除成员';}
function materializeMembers(items:ProjectMember[],busy:string,setRole:(member:ProjectMember,role:'viewer'|'editor')=>void,remove:(member:ProjectMember)=>void){const nodes:ReactNode[]=[];for(const member of items){nodes.push(<div key={member.user_id} className="flex flex-wrap items-center justify-between gap-3 border-b py-4 last:border-b-0"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-medium">{roleIcon(member.role)}<span className="truncate">{member.username||member.email||member.user_id}</span><Badge variant="outline">{roleLabel(member.role)}</Badge></div>{member.email&&<p className="mt-1 truncate text-xs text-muted-foreground">{member.email}</p>}</div>{member.role!=='owner'&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy!==''||member.role==='viewer'} onClick={()=>setRole(member,'viewer')}>查看者</Button><Button size="sm" variant="outline" disabled={busy!==''||member.role==='editor'} onClick={()=>setRole(member,'editor')}>编辑者</Button><Button size="icon" variant="ghost" title="移除成员" disabled={busy!==''} onClick={()=>remove(member)}><Trash2 className="h-4 w-4"/></Button></div>}</div>)}return nodes;}
function materializeAudits(items:CollaborationAudit[]){const nodes:ReactNode[]=[];for(const item of items){nodes.push(<div key={item.id} className="border-b py-3 text-sm last:border-b-0"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{auditLabel(item.action)}</span><span className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</span></div><p className="mt-1 break-all text-xs text-muted-foreground">{item.target_user_id}{item.next_role?` · ${roleLabel(item.next_role)}`:''}</p></div>)}return nodes;}

export default function ProjectCollaborationPage(){
 const params=useParams<{id:string}>();const projectId=params.id;const [access,setAccess]=useState<ProjectAccess|null>(null);const [members,setMembers]=useState<ProjectMember[]>([]);const [audits,setAudits]=useState<CollaborationAudit[]>([]);const [email,setEmail]=useState('');const [role,setRole]=useState<'viewer'|'editor'>('viewer');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setError('');const nextAccess=await collaborationApi.access(projectId);setAccess(nextAccess);if(nextAccess.can_manage){const [nextMembers,nextAudits]=await Promise.all([collaborationApi.members(projectId),collaborationApi.audits(projectId)]);setMembers(nextMembers);setAudits(nextAudits)}},[projectId]);
 useEffect(()=>{void load().catch((value:unknown)=>setError(value instanceof Error?value.message:'协作状态加载失败'));},[load]);
 const run=async(action:string,operation:()=>Promise<void>)=>{setBusy(action);setError('');setMessage('');try{await operation();await load()}catch(value){setError(value instanceof Error?value.message:'协作操作失败')}finally{setBusy('')}};
 const add=()=>{if(!email.trim())return;void run('add',async()=>{await collaborationApi.setMember(projectId,email,'',role);setEmail('');setMessage('成员已添加')})};
 const update=(member:ProjectMember,nextRole:'viewer'|'editor')=>void run(`role-${member.user_id}`,async()=>{await collaborationApi.setMember(projectId,'',member.user_id,nextRole);setMessage('成员角色已更新')});
 const remove=(member:ProjectMember)=>{if(!window.confirm(`确认移除 ${member.email||member.user_id}？`))return;void run(`remove-${member.user_id}`,async()=>{await collaborationApi.removeMember(projectId,member.user_id);setMessage('成员已移除')})};
 const memberNodes=materializeMembers(members,busy,update,remove);const auditNodes=materializeAudits(audits);
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b bg-card"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex min-w-0 items-center gap-3"><Button asChild size="icon" variant="ghost" title="返回项目"><Link href={`/workspace?project=${encodeURIComponent(projectId)}`}><ArrowLeft className="h-4 w-4"/></Link></Button><Users className="h-5 w-5"/><div className="min-w-0"><h1 className="truncate text-base font-semibold">项目协作</h1><p className="truncate text-xs text-muted-foreground">{projectId}</p></div></div><Button size="sm" variant="outline" disabled={busy!==''} onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>刷新</Button></div></header>
 <div className="mx-auto grid max-w-5xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.65fr)]"><section className="space-y-4"><div className="flex items-center justify-between border-b pb-3"><h2 className="text-sm font-semibold">成员与权限</h2><Badge variant="outline">{access?roleLabel(access.role):'加载中'}</Badge></div>{access?.can_manage&&<div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_120px_auto]"><Input aria-label="成员邮箱" placeholder="member@example.com" value={email} onChange={(event)=>setEmail(event.target.value)}/><div className="inline-flex border"><Button type="button" size="sm" variant={role==='viewer'?'default':'ghost'} onClick={()=>setRole('viewer')}>查看</Button><Button type="button" size="sm" variant={role==='editor'?'default':'ghost'} onClick={()=>setRole('editor')}>编辑</Button></div><Button disabled={busy!==''||!email.trim()} onClick={()=>add()}>{busy==='add'?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<UserPlus className="mr-2 h-4 w-4"/>}添加</Button></div>}{access?.can_manage?memberNodes:<Alert><AlertTitle>当前权限：{access?roleLabel(access.role):'未知'}</AlertTitle><AlertDescription>{access?.can_write?'可以查看和编辑项目，但只有所有者能管理成员。':'仅可查看项目，写操作会被服务端阻断。'}</AlertDescription></Alert>}</section>
 <section className="space-y-4"><div className="flex items-center justify-between border-b pb-3"><h2 className="text-sm font-semibold">成员审计</h2><Badge variant="outline">{audits.length}</Badge></div>{access?.can_manage?(auditNodes.length>0?auditNodes:<p className="text-sm text-muted-foreground">暂无成员变更</p>):<p className="text-sm text-muted-foreground">仅所有者可查看成员审计。</p>}</section>{(error||message)&&<Alert className="lg:col-span-2" variant={error?'destructive':'default'}><AlertTitle>{error?'操作失败':'操作完成'}</AlertTitle><AlertDescription className="flex items-center gap-2">{!error&&<Check className="h-4 w-4"/>}{error||message}</AlertDescription></Alert>}</div></main>;
}
